apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finsight.fullname" . }}
  labels:
    {{- include "finsight.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
