{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finsight.serviceAccountName" . }}
  labels:
    {{- include "finsight.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
